### ISSUE TITLE
please make new formal release

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/record-activity#1]
Last release (v99) was 2 years ago.  Lots of trnalsations have entered since then, and a few improvements to metadata.

Please make a new formal release.

**Comment by quozl** [comment]
Agreed, that would be good.  As a baseline before multiple camera support merging.

**Comment by godiard** [comment]
Agreed, I would do it next week.

On Sat, Jun 20, 2015 at 1:36 AM, James Cameron notifications@github.com
wrote:

> Agreed, that would be good. As a baseline before multiple camera support
> merging.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/godiard/record-activity/issues/1#issuecomment-113709104
> .

## 

Gonzalo Odiard

SugarLabs - Software for children learning

**Comment by godiard** [comment]
Released v100
