### ISSUE TITLE
Port to GTK+ 3 and GStreamer 1.0

### ISSUE THREAD

**Issue by quozl** [sugarlabs/record-activity#14]
https://github.com/quozl/record-activity/tree/gtk3 contains a very nearly working port, though some additional improvements are needed.  Developers who want to work on this are invited to coordinate closely with me, thanks.

**Comment by godiard** [comment]
The blocker at the time was the gstreamer pluggins needed to use hardware accelleration in the arm xos.
Probably that is not so needed now or you can ship a gtk2 version with these models

**Comment by quozl** [comment]
Indeed that was then, but this is now.  :grin:  You are quite right.

* GStreamer 1.0 hardware acceleration for the ARM XO-1.75 and XO-4 will be expensive to complete and test, so it is not in my plan; instead I'll continue to use the GStreamer 0.10 version of Record; with the very low rate of new features or fixes, maintaining two versions of Record is easier now than it was before.  This also ties into X server, systemd, and kernel drivers porting that would otherwise be needed if we moved off Fedora 18 for those laptop models.

* GStreamer 0.10 has been dropped by distributions, and so on later models we either carry it as well (not an unreasonable thing to do) or do port Record.  All the other shipped activities have been ported; Measure and Speak in particular, so Record is the last man standing.  And boy oh boy, I can see why it is!  A very popular activity for code changes, with the code base consisting of many different programming styles.

Anyway, the port so far is looking quite good.

**Comment by sanatankc** [comment]
Is it ported? What work is needed to be done more?

**Comment by quozl** [comment]
Thanks for asking.  It's not so simple, sorry.

I've not recently checked what needs to be done, and making that assessment will take some time.  Your best option is to try the branch yourself; you'll need hardware with a camera, or good virtualisation with camera pass-through.

I've pushed another two patches on that branch that had been lurking on my development system.

@walterbender also mentioned having done a port at one stage, but I don't know where he has it stashed.

**Comment by yell0wfl4sh** [comment]
@quozl @walterbender what is the status of this activity?

**Comment by quozl** [comment]
Latest release is GTK+ 2 with GStreamer 0.10.  Can be found in the master branch with corresponding tag.  Is on activities.sugarlabs.org.  Is packaged by Fedora for SoaS.

A port to GTK+ 3 with GStreamer 1.0 can be found in the gtk3 branch, either here or in my fork.  Let me know if you can't find it.  It has a few small bugs, but otherwise works.  You must have real hardware to test with, or simulate using v4l2testsrc instead of v4l2src element.

I've a local prototype activity which renders camera on display, and can add "take a photograph" button fairly quickly.  Much fewer lines of code.  I'll continue on that as I get time.

-- 
James Cameron
http://quozl.netrek.org/

**Comment by quozl** [comment]
Comment on impact; the Record activity is heavily used at home in Madagascar.

[S. Nogry & P. Varly (2018) Everyday Laptop Use by Children in a Southern
Country: A Mixed-Method Approach, Journal of Research on Technology in Education, 50:1, 18-33,
DOI: 10.1080/15391523.2017.1388200](https://www.tandfonline.com/doi/pdf/10.1080/15391523.2017.1388200?needAccess=true)

**Comment by quozl** [comment]
Work in progress port is at
* https://github.com/quozl/record-activity/tree/gtk3

A previous port in 2012 is at
* http://git.sugarlabs.org/~flavio/record/record-gtk3/commits/master

I've no idea which is best, yet.

**Comment by quozl** [comment]
Further work in progress pushed to https://github.com/quozl/record-activity/tree/gtk3

* displays live video on start,
* captures photographs.

**Comment by quozl** [comment]
Further work in progress pushed to https://github.com/quozl/record-activity/tree/gtk3

* all features are now present,
* many bugs fixed,
* some new features added,
* testing is needed.
