### ISSUE TITLE
incomplete copyright and licensing info

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/record-activity#2]
This project has incomplete and arguably misleading copyright and licensing info:

COPYING contains the Expat license which might wrongly lead some to believe the project as a whole having that license: Some files are licensed as LGPL-2 and some as GPL-2+ which the Expat-licensed parts can be "upgraded" to but not the reverse, so arguably render the project as a whole can be licensable only as GPL-2+

aplay.py contains licensing but lacks copyright: Who is the copyright holder who issued that licensing?

hw.py and tray.py is licensed as non-existent _Lesser_ GPL 2 (LGPL pror to 2.1 was called _Library_ GPL), and claims the actual license is included with the project which it isn't.

aplay.py and setup.py is licensed as GPL 2 , and claims the actual license is included with the project which it isn't.

Several files - in particular code files - lack both copyright and licensing: If they are supposed to inherit the licensing of COPYING file then I believe that needs to be stated explicitly somewhere.

I recommend to list copyright line(s) in each and every code file, and include Expat licensing with each file licensed as such, and put GPL 2 in COPYING file, and add COPYING.lgpl with License GPL 2 licensing.

**Comment by godiard** [comment]
Thanks for the detailed analysis. I will add this to my (long) list of pending tasks.
If you want send a patch I will apply it.

**Comment by quozl** [comment]
5d8a0becaa3fd3207b8e6f2e1ab0646bb3c41a22 merged, closing.
